apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: photo-album

namespace: demo

resources:
  - namespace.yaml
  - obc.yaml
  - deploymentconfig.yaml  
  - service.yaml
  - route.yaml

  