kind: Service
apiVersion: v1
metadata:
  labels:
    app: photo-album
  name: photo-album
  namespace: demo
spec:
  ports:
    - name: 80-tcp
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: photo-album
