kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: mysql-cephfs
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
  selector:
    name: mysql
