apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: mysql

namespace: mysql-cephrbd

resources:
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - secret.yaml
  - deploymentconfig.yaml

images:
- name: mysql-image
  newName: registry.redhat.io/rhel8/mysql-80
  newTag: latest
  