kind: Secret
apiVersion: v1
metadata:
  name: mysql
  namespace: mysql-cephrbd
data:
  database-name: cGV0Y2xpbmlj
  database-password: cGV0Y2xpbmlj
  database-root-password: cGV0Y2xpbmlj
  database-user: cGV0Y2xpbmlj
type: Opaque
